---
- name: Config bash
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    bashrc: "{{ ansible_env.HOME }}/.bashrc"
    bash_aliases: "{{ ansible_env.HOME }}/.bash_aliases"

  tasks:
    - name: Install required packages
      package:
        name:
          - bash
          - bash-completion
          - bash-doc
        state: installed
      become: yes

    - name: copy over bashrc files
      copy:
        src: bashrc
        dest: "{{ bashrc }}"
        backup: yes
        mode: 640

    - name: copy over bash_aliases files
      copy:
        src: bash_aliases
        dest: "{{ bash_aliases }}"
        backup: yes
        mode: 640
        tags:
          - copy_files
